# Generated by Django 4.1.7 on 2023-03-09 04:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=2)),
                ('branch_id', models.CharField(blank=True, max_length=2, null=True)),
                ('branch', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=15)),
                ('requester', models.CharField(max_length=100)),
                ('requester_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[('DIRETORIA', 'DIRETORIA'), ('FATURAMENTO', 'FATURAMENTO'), ('FINANCEIRO', 'FINANCEIRO'), ('RH', 'RH'), ('FISCAL', 'FISCAL'), ('MONITORAMENTO', 'MONITORAMENTO'), ('OPERACIONAL', 'OPERACIONAL'), ('FROTA', 'FROTA'), ('EXPEDICAO', 'EXPEDICAO'), ('COMERCIAL', 'COMERCIAL'), ('JURIDICO', 'JURIDICO'), ('DESENVOLVIMENTO', 'DESENVOLVIMENTO'), ('TI', 'TI'), ('FILIAIS', 'FILIAIS'), ('COMPRAS', 'COMPRAS')], max_length=15, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('A_VISTA', 'A VISTA'), ('PARCELADO-1X', 'PARCELADO 1X'), ('PARCELADO-2X', 'PARCELADO 2X'), ('PARCELADO-3X', 'PARCELADO 3X'), ('PARCELADO-4X', 'PARCELADO 4X'), ('PARCELADO-5X', 'PARCELADO 5X'), ('PARCELADO-6X', 'PARCELADO 6X'), ('PARCELADO-7X', 'PARCELADO 7X'), ('PARCELADO-8X', 'PARCELADO 8X'), ('PARCELADO-9X', 'PARCELADO 9X'), ('PARCELADO-10X', 'PARCELADO 10X'), ('PARCELADO-11X', 'PARCELADO 11X')], max_length=15, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 3, 9, 1, 5, 32, 461181))),
                ('obs', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cpr/%Y/%m/%d')),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorcompras', to=settings.AUTH_USER_MODEL)),
                ('last_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimaattcompras', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavelcompras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
