# Generated by Django 4.1.7 on 2023-03-09 07:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 4, 19, 50, 512914)),
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200)),
                ('itens_qty', models.IntegerField()),
                ('solic_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_tools.purchaserequest')),
            ],
        ),
    ]
