# Generated by Django 4.1.7 on 2023-03-09 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_tools', '0002_alter_purchaserequest_pub_date_productrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 4, 20, 5, 875427)),
        ),
    ]
